-- KlicTech Sem Fronteiras — schema PostgreSQL/Supabase
-- Execute no Supabase SQL Editor se quiser criar as tabelas antes do primeiro deploy.

create table if not exists users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  name text not null,
  password_hash text not null,
  balance_cents bigint not null default 0,
  is_admin integer not null default 0,
  public_id text unique,
  profile_photo bytea,
  profile_photo_mime text,
  blocked_at timestamptz,
  created_at timestamptz default current_timestamp
);

create table if not exists wallet_charges (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id),
  provider_id text unique not null,
  external_reference text unique not null,
  amount_cents bigint not null,
  status text default 'PENDING',
  pix_copy_paste text,
  expires_at text,
  created_at timestamptz default current_timestamp,
  paid_at timestamptz
);

create table if not exists wallet_ledger (
  id bigint generated by default as identity primary key,
  event_id text unique not null,
  user_id bigint not null references users(id),
  provider_id text,
  amount_cents bigint not null,
  kind text,
  created_at timestamptz default current_timestamp
);

create table if not exists access_logs (
  user_id bigint references users(id),
  ip text not null,
  user_agent text,
  created_at timestamptz default current_timestamp
);

create table if not exists carts (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  session_key text,
  plan text not null,
  status text default 'active',
  created_at timestamptz default current_timestamp,
  updated_at timestamptz default current_timestamp
);

create table if not exists inventory (
  id bigint generated by default as identity primary key,
  plan text not null,
  model text not null,
  line text,
  ddd text,
  photo bytea,
  photo_mime text,
  smdp text not null,
  activation_code text unique not null,
  sold_at timestamptz,
  sold_to bigint,
  created_at timestamptz default current_timestamp
);

create table if not exists purchases (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id),
  inventory_id bigint not null,
  plan text not null,
  price_cents bigint not null,
  status text default 'approved',
  created_at timestamptz default current_timestamp
);

create table if not exists admin_events (
  id bigint generated by default as identity primary key,
  event text,
  detail text,
  created_at timestamptz default current_timestamp
);

create table if not exists plan_catalog (
  id bigint generated by default as identity primary key,
  plan text unique not null,
  gigas text not null,
  tempo text not null,
  price_cents bigint not null,
  active boolean not null default true,
  featured boolean not null default false,
  created_at timestamptz default current_timestamp
);

create index if not exists idx_inventory_available on inventory(plan, ddd) where sold_at is null;
create index if not exists idx_purchases_user on purchases(user_id, id desc);
create index if not exists idx_wallet_charges_provider on wallet_charges(provider_id);
